In [2]:
 #IMPORTAMOS LIBRERIAS
import requests 
import pandas as pd
import re
import ast

#### 1) Muertes y Casos Confirmados por país hasta el 2022-12-31 por Covid-19:

In [3]:


url = "https://covid-19-statistics.p.rapidapi.com/regions"#Guardamos el link de la appi de todos los países
URL= "https://covid-19-statistics.p.rapidapi.com/reports/total" #Guardamos el link de la appi de los reportes total
headers = {
	"X-RapidAPI-Key": "5715c80c9emsh5051181da9b627fp1d0162jsn4d23a1fc2ead",
	"X-RapidAPI-Host": "covid-19-statistics.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)#Leemos 
df = pd.read_json(response.text)#Convertimos en un dataframe del formato json

col_a = df['data']#leemos el la 1ra columna
a=0        #Añadimos un contador y listas donde almacenaremos 
paises=[]
iso=[]
deaths=[]
casos=[]
for z in range(len(col_a)):#Creamos el bucle con un rango de todos los países
    c=c=col_a[a]           #Guardamos cada elemento
    c=str(c)               #Convertimos en str
    b=re.findall(r"'name':.*'(.*)'",c) #Limpiamos el nombre del país
    paises.append(b)                   #Guardamos el nombre en la lista
    g=re.findall(r"iso.*'(.*)',",c)    #Limpiamos el iso del país
    iso.append(g)                      #guardamos en su lista respectiva
    a=a+1
    querystring ={"iso":g,"date":"2022-12-31"}
    responses = requests.request("GET", URL, headers=headers, params=querystring)
    r=responses.text
    res = ast.literal_eval(r)
    if len(res["data"])!=0:
        muer=res["data"]["deaths"]
        infe=res["data"]["confirmed"]
        deaths.append(muer)
        casos.append(infe)
    else:
        deaths.append("NA")
        casos.append("NA")

In [5]:
datos = {   
    'ISO':iso,             #Creamos un diccionario con las listas 
    'País': paises,
    'Casos': casos,
    'Muertes' : deaths
}

df = pd.DataFrame(datos)# lo convertimos a un dataframe 
df

       ISO                   País      Casos  Muertes
0    [CHN]                [China]    4537107    17062
1    [TWN]  [Taipei and environs]    8847360    15253
2    [USA]                   [US]  100749731  1092674
3    [JPN]                [Japan]   29234677    57274
4    [THA]             [Thailand]    4721808    33594
..     ...                    ...        ...      ...
214  [KIR]             [Kiribati]       3430       13
215  [PLW]                [Palau]       5971        9
216  [TON]                [Tonga]      16211       12
217  [NRU]                [Nauru]       4621        1
218  [TUV]               [Tuvalu]       2805        0

[219 rows x 4 columns]

#### Con este data frame podemos observar el total de casos y muertes por país, siendo USA con la mayor cantidad con 100749731 casos y 1092674 muertes.

#### 2) Muertes y Casos Confirmados en el año 2022 En Estados Unidos por Covid-19:

In [163]:

url = "https://covid-19-statistics.p.rapidapi.com/reports/total" #Guardamos el links de los reportes totales
headers = {                                                      #Agregamos los headers
	"X-RapidAPI-Key": "5715c80c9emsh5051181da9b627fp1d0162jsn4d23a1fc2ead",
	"X-RapidAPI-Host": "covid-19-statistics.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring) #Leemos
#Agregamos contadores :
confirmed=0 
deaths=0


a=0 
b=1
for z in range(12):#Creamos el primer bucle de los meses
  a=a+1
  b=1
  for d in range(32):#Este bucle es de los días
    if a>=10:        #Si a mayor a 10 no se le aumenta un "0" antes de este
        a=str(a)
        g=a
    else:            #de lo contrario sí
        a=str(a)
        g="0"+a
    if b>=10:       #Lo mismo para el contador b
        b=str(b)
        f=b
    else:
        b=str(b)
        f="0"+b
    f="2022-"+g+"-"+f #Creamos aca la fecha final
    print(f)          
    querystring = {"iso":"USA","date":f}#Agregamos los parametros
    response = requests.request("GET", url, headers=headers, params=querystring)#leemos
    r=response.text   
    res = ast.literal_eval(r) #Convertimos a un diccionario
    try:
        if len(res["data"])!=0: 
            muer=res["data"]["deaths_diff"] #Filtramos el número de muertes por día 
            infe=res["data"]["confirmed_diff"] #Filtramos el número de casos por día 
            confirmed=confirmed+infe #Sumamos 
            deaths=deaths+muer       #Sumamos
    except:
        print("")
    a=int(a)
    b=int(b)
    b=b+1

2022-01-01
2022-01-02
2022-01-03
2022-01-04
2022-01-05
2022-01-06
2022-01-07
2022-01-08
2022-01-09
2022-01-10
2022-01-11
2022-01-12
2022-01-13
2022-01-14
2022-01-15
2022-01-16
2022-01-17
2022-01-18
2022-01-19
2022-01-20
2022-01-21
2022-01-22
2022-01-23
2022-01-24
2022-01-25
2022-01-26
2022-01-27
2022-01-28
2022-01-29
2022-01-30
2022-01-31
2022-01-32

2022-02-01
2022-02-02
2022-02-03
2022-02-04
2022-02-05
2022-02-06
2022-02-07
2022-02-08
2022-02-09
2022-02-10
2022-02-11
2022-02-12
2022-02-13
2022-02-14
2022-02-15
2022-02-16
2022-02-17
2022-02-18
2022-02-19
2022-02-20
2022-02-21
2022-02-22
2022-02-23
2022-02-24
2022-02-25
2022-02-26
2022-02-27
2022-02-28
2022-02-29

2022-02-30

2022-02-31

2022-02-32

2022-03-01
2022-03-02
2022-03-03
2022-03-04
2022-03-05
2022-03-06
2022-03-07
2022-03-08
2022-03-09
2022-03-10
2022-03-11
2022-03-12
2022-03-13
2022-03-14
2022-03-15
2022-03-16
2022-03-17
2022-03-18
2022-03-19
2022-03-20
2022-03-21
2022-03-22
2022-03-23
2022-03-24
2022-03-25
2022-03-26
2022-03-27
2022-03-28
2022-03-29
2022-03-30
2022-03-31
2022-03-32

2022-04-01
2022-04-02
2022-04-03
2022-04-04
2022-04-05
2022-04-06
2022-04-07
2022-04-08
2022-04-09
2022-04-10
2022-04-11
2022-04-12
2022-04-13
2022-04-14
2022-04-15
2022-04-16
2022-04-17
2022-04-18
2022-04-19
2022-04-20
2022-04-21
2022-04-22
2022-04-23
2022-04-24
2022-04-25
2022-04-26
2022-04-27
2022-04-28
2022-04-29
2022-04-30
2022-04-31

2022-04-32

2022-05-01
2022-05-02
2022-05-03
2022-05-04
2022-05-05
2022-05-06
2022-05-07
2022-05-08
2022-05-09
2022-05-10
2022-05-11
2022-05-12
2022-05-13
2022-05-14
2022-05-15
2022-05-16
2022-05-17
2022-05-18
2022-05-19
2022-05-20
2022-05-21
2022-05-22
2022-05-23
2022-05-24
2022-05-25
2022-05-26
2022-05-27
2022-05-28
2022-05-29
2022-05-30
2022-05-31
2022-05-32

2022-06-01
2022-06-02
2022-06-03
2022-06-04
2022-06-05
2022-06-06
2022-06-07
2022-06-08
2022-06-09
2022-06-10
2022-06-11
2022-06-12
2022-06-13
2022-06-14
2022-06-15
2022-06-16
2022-06-17
2022-06-18
2022-06-19
2022-06-20
2022-06-21
2022-06-22
2022-06-23
2022-06-24
2022-06-25
2022-06-26
2022-06-27
2022-06-28
2022-06-29
2022-06-30
2022-06-31

2022-06-32

2022-07-01
2022-07-02
2022-07-03
2022-07-04
2022-07-05
2022-07-06
2022-07-07
2022-07-08
2022-07-09
2022-07-10
2022-07-11
2022-07-12
2022-07-13
2022-07-14
2022-07-15
2022-07-16
2022-07-17
2022-07-18
2022-07-19
2022-07-20
2022-07-21
2022-07-22
2022-07-23
2022-07-24
2022-07-25
2022-07-26
2022-07-27
2022-07-28
2022-07-29
2022-07-30
2022-07-31
2022-07-32

2022-08-01
2022-08-02
2022-08-03
2022-08-04
2022-08-05
2022-08-06
2022-08-07
2022-08-08
2022-08-09
2022-08-10
2022-08-11
2022-08-12
2022-08-13
2022-08-14
2022-08-15
2022-08-16
2022-08-17
2022-08-18
2022-08-19
2022-08-20
2022-08-21
2022-08-22
2022-08-23
2022-08-24
2022-08-25
2022-08-26
2022-08-27
2022-08-28
2022-08-29
2022-08-30
2022-08-31
2022-08-32

2022-09-01
2022-09-02
2022-09-03
2022-09-04
2022-09-05
2022-09-06
2022-09-07
2022-09-08
2022-09-09
2022-09-10
2022-09-11
2022-09-12
2022-09-13
2022-09-14
2022-09-15
2022-09-16
2022-09-17
2022-09-18
2022-09-19
2022-09-20
2022-09-21
2022-09-22
2022-09-23
2022-09-24
2022-09-25
2022-09-26
2022-09-27
2022-09-28
2022-09-29
2022-09-30
2022-09-31

2022-09-32

2022-10-01
2022-10-02
2022-10-03
2022-10-04
2022-10-05
2022-10-06
2022-10-07
2022-10-08
2022-10-09
2022-10-10
2022-10-11
2022-10-12
2022-10-13
2022-10-14
2022-10-15
2022-10-16
2022-10-17
2022-10-18
2022-10-19
2022-10-20
2022-10-21
2022-10-22
2022-10-23
2022-10-24
2022-10-25
2022-10-26
2022-10-27
2022-10-28
2022-10-29
2022-10-30
2022-10-31
2022-10-32

2022-11-01
2022-11-02
2022-11-03
2022-11-04
2022-11-05
2022-11-06
2022-11-07
2022-11-08
2022-11-09
2022-11-10
2022-11-11
2022-11-12
2022-11-13
2022-11-14
2022-11-15
2022-11-16
2022-11-17
2022-11-18
2022-11-19
2022-11-20
2022-11-21
2022-11-22
2022-11-23
2022-11-24
2022-11-25
2022-11-26
2022-11-27
2022-11-28
2022-11-29
2022-11-30
2022-11-31

2022-11-32

2022-12-01
2022-12-02
2022-12-03
2022-12-04
2022-12-05
2022-12-06
2022-12-07
2022-12-08
2022-12-09
2022-12-10
2022-12-11
2022-12-12
2022-12-13
2022-12-14
2022-12-15
2022-12-16
2022-12-17
2022-12-18
2022-12-19
2022-12-20
2022-12-21
2022-12-22
2022-12-23
2022-12-24
2022-12-25
2022-12-26
2022-12-27
2022-12-28
2022-12-29
2022-12-30
2022-12-31
2022-12-32

In [164]:
 #La cantidad de muertes en EU en el año de 2022 por covid-19
print(deaths)

267138

In [165]:
#La cantidad de casos en EU en el año de 2022 de covid-19
print(confirmed)

46005749